site_name: Data Honor
site_url: https://shenxiangzhuang.github.io
site_author: Xiangzhuang Shen
site_description: >-
  Xiangzhuang Shen's blog

repo_name: Xiangzhuang Shen'S Blog
repo_url: https://github.com/shenxiangzhuang/shenxiangzhuang.github.io
copyright: Copyright &copy; 2017 - 2024 Xiangzhuang Shen

theme:
  name: material
  favicon: assets/logo/glimpse-ai-logo-small.png
  custom_dir: docs/templates
  icon:
    logo: material/state-machine
    repo: fontawesome/brands/github
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

  features:
    - content.action.edit
    - content.action.view
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - tables
  - neoteroi.timeline
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets:
      url_download: true
      url_max_size: 33554432
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - admonition
  - footnotes

extra_css:
  - css/neoteroi-mkdocs.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6

plugins:
  - autorefs
  - mkdocs-pdf
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog:
      draft: true
  - search:
      lang: zh
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: shenxiangzhuang/shenxiangzhuang.github.io
      branch: master
      #      cache_dir: docs/assets/git-committers
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]

  - minify:
      minify_html: true
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "docs/ieee.csl"
      cite_inline: false

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  analytics:
    provider: google
    property: G-KEEHE7VY5K
  #    feedback:
  #      title: Was this page helpful?
  #      ratings:
  #        - icon: material/emoticon-happy-outline
  #          name: This page was helpful
  #          data: 1
  #          note: >-
  #            Thanks for your feedback!
  #        - icon: material/emoticon-sad-outline
  #          name: This page could be improved
  #          data: 0
  #          note: >-
  #            Thanks for your feedback! Help us improve this page by
  #            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  social:
    - icon: material/rss
      link: https://datahonor.com/feed_rss_created

    - icon: fontawesome/brands/github
      link: https://github.com/shenxiangzhuang

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/MathewShen42

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mathewshen

    - icon: material/email
      link: mailto:datahonor@gmail.com

    - icon: simple/wechat
      link: https://mp.weixin.qq.com/s/wOqp6nHBAenK9wP2vIUS9g

    - icon: simple/zhihu
      link: https://www.zhihu.com/people/shen-xiang-zhuang



nav:
  - About: index.md
  - Data Science:
      - Math & Statistics:
          - datascience/statistics/index.md
          - Probability and mathematical statistics books recommendation: datascience/statistics/probability-and-mathematical-statistics-books.md
          - Three doors and three prisoners: datascience/statistics/three-doors-and-three-prisoners.md
          - ROC-AUC: datascience/statistics/roc-auc.md
          - P value or Effect size: datascience/statistics/effect-size.md

      - Statistical Machine Learning:
          - datascience/ml/index.md
          - 最大似然估计与经验风险最小化: datascience/ml/mle-mer.md
      - Deep Learning:
          - datascience/dl/index.md
          - Papers: datascience/dl/paper.md
          - CUDA: datascience/dl/cuda.md

  - Computer Science:
      - Programming:
          - cs/programming/index.md
          - Python:
              - cs/programming/python/index.md
              - How to build a Python Package: cs/programming/python/build_python_pkg.md
              - The Art of Python Programming(TAPP): cs/programming/python/tapp_0_motivation.md
              - "TAPP1: Decorator and Closure": cs/programming/python/tapp_1_decorator.md
              - "TAPP2: Context Managers": cs/programming/python/tapp_2_context_manager.md
              - "TAPP3: Annotations": cs/programming/python/tapp_3_annotations.md
              - Python与数据分析: cs/programming/python/python_data_analysis.md

          - Rust:
            - cs/programming/rust/index.md

          - JS&TS:
            - cs/programming/js/index.md

          - Elixir:
            - cs/programming/elixir/index.md

          - Scala:
            - SBT Usage: cs/programming/scala/sbt_usage.md

      - Algorithm:
        - cs/algorithm/index.md

      - OS:
        - cs/os/index.md
        - Ubuntu Usage: cs/os/ubuntu-usage.md
      - DB:
        - cs/db/index.md
        - ClickHouse:
            - 自建ClickHouse: cs/db/clickhouse/self-host.md
            - ClickHouse使用: cs/db/clickhouse/usage.md
      - Network:
        - cs/network/index.md
      - Docker:
        - cs/docker/index.md
      - Distributed System:
          - Hive:
              - Hive Tips: cs/distribution/hive/tips.md
          - Hadoop:
              - Hadoop on Linux: cs/distribution/hadoop/hadoop-linux.md
          - Spark:
              - Spark on Linux: cs/distribution/spark/spark-linux.md
              - Spark on Cloud: cs/distribution/spark/spark-cloud.md

  - Software Engineering:
      - se/index.md
      - Backend:
          - se/backend/index.md
          - Python:
              - se/backend/python/index.md
              - FastAPI Practice: se/backend/python/fastapi.md
      - Frontend:
          - se/frontend/index.md
      - Database:
          - se/db/index.md
          - MySQL: se/db/mysql.md
          - MongoDB: se/db/mongodb.md

      - DDD:
          - se/ddd/index.md
          - "Book: Learning DDD": se/ddd/learning-ddd.md

      - Test:
          - "Book: Unit Testing": se/test/unit-testing.md

      - Observability:
          - se/observability/index.md
          - Skywalking: se/observability/skywalking.md
          - "ElasticSearch & Kibana": se/observability/es_kibana.md
      - Distributed System:
          - se/distribution/index.md
      - DevOps:
          - se/devops/index.md
          - Vercel Domain: se/devops/vercel.md

  - Career Odyssey:
      - odyssey/index.md
      - AIOps:
          - odyssey/aiops/index.md
          - Time Series Anomaly Detection:
              - Paper: odyssey/aiops/tsad/paper.md
              - Product: odyssey/aiops/tsad/product.md
          - Time Series Forecasting:
              - Paper: odyssey/aiops/tsfcst/paper.md
          - Root Cause Analysis:
              - Paper: odyssey/aiops/rca/paper.md
          - Conference: odyssey/aiops/conference.md

      - MLSys:
          - odyssey/mlsys/index.md
          - Research:
              - Paper: odyssey/mlsys/research/paper.md

      - Crowdsourcing:
          - odyssey/chc/index.md
          - Paper: odyssey/chc/paper.md

      - Large Language Model:
          - odyssey/llm/index.md
          - Paper: odyssey/llm/paper.md
          - Engineering: odyssey/llm/engineering.md

  - Tool:
      - tool/index.md
      - Linux(Ubuntu): tool/ubuntu.md
      - Diagram: tool/diagram.md
      - Latex: tool/latex.md
      - Disk: tool/disk.md

  - Project:
      - project/index.md

  - Life:
      - 前言: life/index.md
      - 文史哲:
          - 书单: life/literature/books.md
      - 菜谱:
          - 煮: life/cookbook/boil.md
          - 炒: life/cookbook/saute.md
          - 炖: life/cookbook/stew.md
  - Blog:
      - blog/index.md
