site_name: Data Honor
site_url: https://shenxiangzhuang.github.io
site_author: Xiangzhuang Shen
site_description: >-
  Xiangzhuang Shen's blog

repo_name: Xiangzhuang Shen
repo_url: https://github.com/shenxiangzhuang

copyright: Copyright &copy; 2017 Xiangzhuang Shen

theme:
  name: material
  custom_dir: docs/templates
  icon:
    repo: fontawesome/brands/github
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono


markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets:
      url_download: true
      url_max_size: 33554432
  - pymdownx.tabbed
  - abbr
  - admonition
  - footnotes


extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - i18n:
      default_language: zh
      material_alternate: true
      languages:
        zh:
          name: 简体中文
          build: true
        en:
          name: English
          build: true
  - search:
      lang: ja
  - git-revision-date-localized
  - minify:
      minify_html: true
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "docs/ieee.csl"
      cite_inline: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shenxiangzhuang

nav:
  - About: index.md
  - Data Science:
    - datascience/index.md
    - Math:
        - datascience/math/learn.md
    - Statistics:
      - datascience/statistics/learn.md
      - Probability and mathematical statistics books recommendation: datascience/statistics/probability-and-mathematical-statistics-books.md
      - Three doors and three prisoners: datascience/statistics/three-doors-and-three-prisoners.md
      - ROC-AUC: datascience/statistics/roc-auc.md
      - P value or Effect size: datascience/statistics/effect-size.md

    - Statistical Machine Learning:
      - datascience/ml/learn.md
      - 最大似然估计与经验风险最小化: datascience/ml/mle-mer.md
      - 原始感知机算法实现: datascience/ml/perceptron.md
      - 对偶感知机算法实现: datascience/ml/dual-perceptron.md
      - 朴素贝叶斯算法实现: datascience/ml/naive-bayes.md

    - Deep Learning:
        - datascience/dl/learn.md
        - Papers: datascience/dl/paper.md

  - Computer Science:
    - cs/index.md
    - Programming:
      - General: cs/programming/general/learn.md
      - Python:
        - cs/programming/python/learn.md
        - How to build a Python Package: cs/programming/python/build_python_pkg.md
        - The Art of Python Programming(TAPP): cs/programming/python/tapp_0_motivation.md
        - "TAPP1: Decorator and Closure": cs/programming/python/tapp_1_decorator.md
        - "TAPP2: Context Managers": cs/programming/python/tapp_2_context_manager.md
        - "TAPP3: Annotations": cs/programming/python/tapp_3_annotations.md
        - Python与数据分析: cs/programming/python/python_data_analysis.md

      - Scala:
        - SBT Usage: cs/programming/scala/sbt_usage.md

    - Algorithm:
        - cs/algorithm/learn.md

    - OS:
        - cs/os/learn.md
        - Ubuntu Usage: cs/os/ubuntu-usage.md
    - DB:
        - cs/db/learn.md
    - Network:
        - cs/network/learn.md
    - K8S:
        - Docker:
          - cs/k8s/docker/learn.md
        - Kubernetes:
          - cs/k8s/kubernetes/learn.md
    - Distributed System:
      - Hadoop:
        - Hadoop on Linux: cs/distribution/hadoop/hadoop-linux.md
      - HBase:
        - HBase on Linux: cs/distribution/hbase/hbase-linux.md
      - Spark:
        - Spark on Linux: cs/distribution/spark/spark-linux.md
        - Spark on Cloud: cs/distribution/spark/spark-cloud.md

  - Data Mining Odyssey:
    - odyssey/index.md
    - AIOps:
      - Time Series Anomaly Detection:
        - Paper: odyssey/aiops/tsad/paper.md
        - Product: odyssey/aiops/tsad/product.md

      - Root Cause Analysis:
        - Paper: odyssey/aiops/rca/paper.md
      - Conference: odyssey/aiops/conference.md

    - MLSys:
      - odyssey/mlsys/learn.md
      - MLOps:
        - Tools: odyssey/mlsys/mlops/tool.md
      - Research:
        - Paper: odyssey/mlsys/research/paper.md

    - Crowdsourcing and Human Computation:
        - odyssey/chc/learn.md
        - Paper: odyssey/chc/paper.md
        - Product: odyssey/chc/product.md

  - Software Engineering:
      - Backend: se/backend.md
      - Frontend: se/frontend.md
      - DevOps: se/devops.md
      - Distributed System: se/distributed-system.md
      - Tools: se/tools.md
  - Project:
      - project/index.md
      - PySESD: project/pysesd.md
      - MPPT: project/mppt.md
      - ToyData: project/toydata.md
      - ToyML: project/toyml.md
      - ToyDL: project/toydl.md

  - Life:
    - 前言: life/index.md
    - 文史哲:
      - 书单: life/literature/books.md
    - 菜谱:
      - 煮: life/cookbook/boil.md
      - 炒: life/cookbook/saute.md

    - 随笔:
      - 十岁那年: life/sketch/ten.md
      - 2019年: life/sketch/2019.md
      - 所谓偶然: life/sketch/chance.md
      - 我的大学: life/sketch/college.md
      - 考研杂记: life/sketch/graduate.md
      - 罪在蒙昧: life/sketch/obscurant.md
      - 奇怪的梦: life/sketch/strange-dream.md
      - 当我们在谈论吃饭时: life/sketch/sysu-card.md
      - 寻找无双: life/sketch/searching.md
